"""AI-generated relevance + personalization insights.

A RelevanceInsight answers, for a given principal and a discovered organization
and/or person: why is this relevant, why should they speak with the principal,
what is the strategic connection, what common ground exists, and what experience
is most relevant. Generated by the insight engine (Anthropic Claude).
"""
from __future__ import annotations

from typing import Optional

from sqlalchemy import Float, ForeignKey, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin


class RelevanceInsight(Base, TimestampMixin):
    __tablename__ = "relevance_insights"
    __table_args__ = (
        UniqueConstraint("principal_id", "contact_id", name="uq_principal_contact"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    principal_id: Mapped[int] = mapped_column(
        ForeignKey("principals.id"), index=True, nullable=False
    )
    # An insight can target a person, an organization, or both.
    contact_id: Mapped[Optional[int]] = mapped_column(ForeignKey("contacts.id"), index=True)
    company_id: Mapped[Optional[int]] = mapped_column(ForeignKey("companies.id"), index=True)

    relevance_score: Mapped[float] = mapped_column(Float, nullable=False)

    # --- The strategic narrative ---
    why_relevant: Mapped[Optional[str]] = mapped_column(Text)
    why_speak_with_principal: Mapped[Optional[str]] = mapped_column(Text)
    strategic_connection: Mapped[Optional[str]] = mapped_column(Text)
    common_ground: Mapped[Optional[str]] = mapped_column(Text)
    relevant_experience: Mapped[Optional[str]] = mapped_column(Text)

    # Signals that triggered relevance (acquisitions, capital raises, leadership
    # changes, expansion, etc.) and concrete conversation talking points.
    signals: Mapped[Optional[list]] = mapped_column(JSON)
    talking_points: Mapped[Optional[list]] = mapped_column(JSON)

    # Concise, research-grounded fields (web/LinkedIn).
    snapshot: Mapped[Optional[str]] = mapped_column(Text)
    key_facts: Mapped[Optional[list]] = mapped_column(JSON)
    sources: Mapped[Optional[list]] = mapped_column(JSON)
    identity_verified: Mapped[bool] = mapped_column(default=True, nullable=False)
    identity_warnings: Mapped[Optional[list]] = mapped_column(JSON)

    opportunity_type: Mapped[Optional[str]] = mapped_column(String(40))
    generated_by: Mapped[Optional[str]] = mapped_column(String(100))

    principal = relationship("Principal", back_populates="insights")
    contact = relationship("Contact", back_populates="insights")
    company = relationship("Company", back_populates="insights")
